Borrowing view
FACG5/tamer-project pull request #101
Opened 2018-10-04 00:55 UTC by ali-7

## Description

create the borrowing section view 

### Type of change

New features #25 
Description : create style and basic js for borrowing section

New features #26 
Description : create the borrowing section view and it's render function

2018-10-04 06:06 UTC, lubnaabd approved these changes

2018-10-07 07:14 UTC, RamyAlshurafa requested changes
Where is the test file?

2018-10-07 07:14 UTC, RamyAlshurafa commented on src/controllers/index.js
> +
remove this line

2018-10-07 07:14 UTC, RamyAlshurafa commented on public/js/borrow.js
> +
remove this line

2018-10-07 08:14 UTC, RamyAlshurafa approved these changes

2018-10-07 08:21 UTC, merged