Add store book
FACG5/tamer-project pull request #112
Opened 2018-10-08 16:25 UTC by lubnaabd

## Description

create addNewBook front-end and back-end code

### Type of change

New features #64
Description : create book_store.js that contain fetch function that make a request (post) to back-end and contain validation function.

New features #65 
Description : 
* add  function that deal with the request from the front-end in book.js in the controller 

New features #16
Description :
- create setStore query, that add all input in db.

New features testing
- test route addBookStore.
- test setStore query.

2018-10-08 17:09 UTC, RamyAlshurafa requested changes
small notes

2018-10-08 17:09 UTC, RamyAlshurafa commented on public/js/book_store.js
> +      .catch(error => swal('Error while adding category !', error.errorMessage, 'error'));
`Error while adding category` while you are adding books!!

2018-10-08 17:09 UTC, RamyAlshurafa commented on src/controllers/test/test.js
> +      t.equal(res.res.statusMessage, 'OK', 'statusMessage should return OK');
`statusMessage` for `200` is `'OK'` always so this is same as line 321
I think it's better to check `JSON.parse(res.text).message` is it the same message you sent?

2018-10-08 17:09 UTC, RamyAlshurafa commented on public/css/book.css
> +.button--view {
add a white line here

2018-10-08 20:23 UTC, RamyAlshurafa approved these changes
#### Approved :ok_hand:

2018-10-09 08:12 UTC, ali-7 approved these changes

2018-10-09 09:25 UTC, RamyAlshurafa approved these changes

2018-10-09 10:12 UTC, merged