View borrowers page
FACG5/tamer-project pull request #119
Opened 2018-10-09 13:20 UTC by Asmaa-ezz

## Description

convert static view to dynamic for borrower 

### Type of change

New features #71 
add router in view borrower and test

New features #17
add getUsers quieres and test 
getBorrower return add data in borrower in database
 
Fixes #70
Description :
add search function in borrower
edit in hbs file to view data

2018-10-09 13:52 UTC, ali-7 approved these changes

2018-10-09 16:47 UTC, RamyAlshurafa requested changes
a small note

2018-10-09 16:47 UTC, RamyAlshurafa commented on src/database/queries/test/test.js
remove this line

2018-10-10 08:40 UTC, RamyAlshurafa approved these changes
#### Approved :confetti_ball:

2018-10-10 08:41 UTC, merged