Sms send
FACG5/tamer-project pull request #143
Opened 2018-10-14 10:54 UTC by Asmaa-ezz

## Description

Send messages sms to user is late to deliver

### Type of change

New features #132 
Description : 
An admin can send a reminder to the user

2018-10-14 16:24 UTC, ali-7 requested changes

2018-10-14 16:24 UTC, ali-7 commented on public/js/book.js
> +      console.log(swal('نجاح', 'تمت ارسال الرسالة بنجاح', 'success'));
remove console.log :))

2018-10-14 18:35 UTC, ali-7 approved these changes

2018-10-15 07:02 UTC, RamyAlshurafa commented on src/controllers/books.js
> +      next(error);
`next(error)` will send `HTML` page, while you sent an `AJAX` request

2018-10-15 07:03 UTC, RamyAlshurafa approved these changes

2018-10-15 07:09 UTC, lubnaabd commented
Closes #132

2018-10-15 07:10 UTC, merged