Add back-end login
FACG5/tamer-project pull request #96
Opened 2018-10-03 13:56 UTC by Asmaa-ezz

## Description
back end to the login page 

login.hbs: #26
  * Page contain form includes two inputs username and password.

### Type of change
New features #6 
Description : create new router for the login

2018-10-03 14:14 UTC, ali-7 approved these changes

2018-10-03 14:14 UTC, lubnaabd approved these changes

2018-10-03 14:31 UTC, RamyAlshurafa requested changes
## Where is the Test files?
Add Labels for your pull request

2018-10-04 09:21 UTC, RamyAlshurafa approved these changes

2018-10-04 09:27 UTC, RamyAlshurafa requested changes

2018-10-04 09:27 UTC, RamyAlshurafa commented on test/test.js
> +    .get('/admin/borrowedUsers')
why add these tests while they're not related to your branch
`.get('/admin/users')`
`.get('/admin/borrowedUsers')`

2018-10-04 09:38 UTC, RamyAlshurafa approved these changes
### Approved.
#### For next Time: Add descriptive commits `Fix` will not be accepted anymore.

2018-10-04 09:39 UTC, merged