Add front-end login and img
FACG5/tamer-project pull request #97
Opened 2018-10-03 14:15 UTC by Asmaa-ezz

## Description
login.js #25
  * File contain validation function and fetch function.
login.css #25
  * File contain style Page login.

### Type of change

New features #5
Description : front-end login

2018-10-03 14:18 UTC, ali-7 approved these changes

2018-10-03 14:21 UTC, lubnaabd approved these changes

2018-10-03 14:53 UTC, RamyAlshurafa requested changes
## * Fix indentation (use 'two spaces' instead of `tab` ).

2018-10-04 09:49 UTC, RamyAlshurafa commented on public/css/login.css
> +* {
from line 1 to 16 are already exists in `admin_style.css`

2018-10-04 09:53 UTC, RamyAlshurafa approved these changes

2018-10-04 10:31 UTC, merged