Admin home page
FACG5/tamer-project pull request #98
Opened 2018-10-03 19:13 UTC by lubnaabd

## Description
**front end to the home page**
admin_style.css #25
  * File contain style homePage.

**back end to the home page**
admin_homePage.hbs: #26
* Page contain form includes statistics such as numbers books/user/borrowing.
test.js
* test router for the  for the homePage

### Type of change

New features #32
Description : front-end homePage.

New features #33
Description : 
* create new router for the homePage.
* test router for the  for the homePage.

2018-10-03 19:59 UTC, ali-7 approved these changes

2018-10-04 07:02 UTC, RamyAlshurafa requested changes
before opening new PR make sure that everything works fine (server, tests)
the page needs to responsive

2018-10-04 07:02 UTC, RamyAlshurafa commented on src/controllers/index.js
> +const borrowedUsers = require('./borrowed_users');
`user.js`, `books.js`, `borrow.js` and `borrowed_users.js`
Not exists on master or in your branch

2018-10-04 07:32 UTC, RamyAlshurafa approved these changes

2018-10-04 07:35 UTC, merged