User page
FACG5/tamer-project pull request #99
Opened 2018-10-03 22:28 UTC by lubnaabd

## Description
**front end to the user page**
user.css #25
  * File contain style user Page.

**back end to the home page**
view_user.hbs: #26
 - Page contain table view all data in user
  * user name
  * address
  * phone

 - Page contain table view all Borrowed user
  * user name
  * address
  * phone
  * startDate
  * endDate
### Type of change

New features #67
Description : front-end view_user.

New features #70
Description : front-end view_Borrowed User.

New features #11
Description : 
* create new router for the viewUser.
* create new router for the Borrowed User.

2018-10-03 22:30 UTC, ali-7 approved these changes

2018-10-04 07:05 UTC, asmaa-ezz approved these changes

2018-10-04 07:36 UTC, RamyAlshurafa requested changes
Pull the master branch and add your routes into the controller

2018-10-04 07:36 UTC, RamyAlshurafa commented on src/views/view_user.hbs
> +      <a data-toggle="tab" aria-expanded="false" href="/admin/borrowedUsers">المستعريين</a>
المستعريين => المستعيرين
:smiling_imp:

2018-10-04 08:14 UTC, RamyAlshurafa requested changes

2018-10-04 08:14 UTC, RamyAlshurafa commented on src/controllers/index.js
> +const user = require('./user.js');
you can use destructuring here

2018-10-04 08:14 UTC, RamyAlshurafa commented on src/controllers/index.js
> +
remove this line

2018-10-04 08:14 UTC, RamyAlshurafa commented on src/controllers/user.js
> +
remove this line

2018-10-04 08:20 UTC, RamyAlshurafa reviewed
next time: use different commit message for each commit

2018-10-04 08:25 UTC, RamyAlshurafa approved these changes

2018-10-04 08:26 UTC, merged